# Generated by Django 5.2.5 on 2025-09-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_created_at_alter_account_beneficiary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
